_config.yml, app/_includes/scripts.html, app/css/devit-custom.css, app/index.html, app/js/devit-custom.js
=> Resolves#23

.jshintrc, app/index.html, app/js/devit-custom.js
We need to provide a subscribe to mailing list section to our web site.
Social media are not enough to inform people that are interested in DEVit with the latest news.
I don't have any preferences with the mailing list tool we will use. I like mailchimp but feel free to choose any tool you are familiar with
=> Create a subscribe section

app/_includes/tickets.html, app/css/style.css, app/index.html
* Tickets moved to Template's layout
* Early Bird and Normal
* Links to http://devitconf2015.eventzilla.net
=> Tickets refactored

app/_includes/speakers.html
This PR addresses the issue #59
=> removed Alberto from speakers

app/_includes/codeofconduct.html, app/index.html
Taken from http://confcodeofconduct.com/
=> Add Code of Conduct. Resolves #36

app/_includes/session-fairlight.html, app/_includes/session-spaceball.html, app/_includes/single-scripts.html, app/_layouts/single.html, app/single-fairlight.html, app/single-spaceball.html, app/single-speakers.html
This closes issue skgtech/devit#124
=> Create 3 responsive pages for the MiiPharos app. One with the speakers and one with each session

app/index.html
=> Change html title

app/_includes/codeofconduct.html
update code of conduct structure,
add 3 contacts for help reach out (2 personal and one global),
add section titles,
add quick version,
add references and links
add missing section on the top
closes #138
=> Update code of conduct

app/_includes/scripts.html, app/_includes/slack-invite.html, app/css/devit-custom.css, app/index.html, app/js/devit-custom.js, app/js/slack-invite.js
=> Feature: Slack invite #191

app/_includes/navigation.html, app/_includes/sessions.html, app/css/devit-custom.css, app/css/style.css, app/index.html
=> Announce Schedule #194

app/_includes/sessions.html, app/css/devit-custom.css
=> added workshops to the schedule, resolves #200

app/_layouts/default.html
Reverts skgtech/devit#150
site.url is empty! Don't know the reason.
=> Revert "Change domain with {{site.url}}"

_includes/navigation.html, _includes/scripts.html, _js/global.js, _js/homepage.js, _js/utils/common.js, _js/utils/metrics.js, _layouts/default.html
This reverts commit f7a1cfac26fd63a0e468c465eaaa222020711c20.
=> Pixel try two

_data/schedule/2017.yml, _data/workshops/2017.yml, pages/schedule/index.html
update Azure workshop
add IBM workshop
fix php symfony data
=> Update workshops data

_data/schedule/2017.yml
Do not try to read the branch name
=> Update Leonie's talk

gulpfile.js, package-lock.json, package.json
This adds scss inline sourcemaps, which enables live and persistent editing of source scss files inside Chrome Dev Tools.
=> Enable css sourcemaps

_data/talks/2018.yml
@kbariotis please review this since I'm not certain whether I used the right structure, whether Tim's workshop is `ticket: single` and whether the link in Tim's description should stay as a link or be converted into plain text.
=> Add talk details for Tim Perry and Dave Platt

_includes/components/speaker.html, _scss/blocks/speakers.scss, _scss/blocks/tags.scss, _scss/bootstrap-override.scss
This adds an interaction like the following in the speakers section for medium+ screens.
=> Update speaker card design

_data/schedule/2018.yml, _data/talks/2018.yml, pages/schedule/index.html
I added some ids to the schedule/2018.yml and talks/2018.yml so I can cross reference the talks and get the right speakerid,title etc
=> Placeholder schedule

_scss/blocks/sessions.scss
Plus remove blue background bleeding in speakers avatars
=> Add fixes for workshops page in mobiles

_data/schedule/2018.yml, _data/talks/2018.yml, _includes/components/scheduleAllWorkshops.html, _includes/components/scheduleEntry.html, _includes/components/session.html, _scss/blocks/schedule.scss, pages/schedule/index.html, pages/workshops/index.html
Schedule fixes done & schedule hours went + 15 minutes after the TBA talk at 14:15
=> Schedule Fixes
